### ISSUE TITLE
Enable pruning for all CRDs in this repo

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/iac-flux-workspace-definitions#10]
Workspaces and workspace user bindings in any cluster should reflect what is in this repo. 

Currently, deleting workspaces or users in the repo is not reconciled to the clusters as pruning is disabled. 

This is not expected behaviour where the GitHub serves as the source of truth.

**Comment by vvcb** [comment]
@qcaas-nhs-sjt - can we add this to the backlog to address at some point please? Not urgent.

**Comment by qcaas-nhs-sjt** [comment]
Pull request for this has been generated above
